"""Keep only MiMo-V2.5-Pro's padded page-64 cached-prefill kernels."""


def filter_config(c) -> bool:
    return (
        c.gfx_arch == "gfx942"
        and c.family == "batch_prefill"
        and c.data_type == "fp8bf16"
        and c.mode == "group"
        and c.hdim_q == 192
        and c.hdim_v == 192
        and c.pipeline == "qr_async"
        and c.page_size == 64
        and c.kv_memory_layout == "vectorized"
        and c.kv_lookup_table == "sglang"
        and c.qscale == "pertensor"
        and c.mask == "bottom_right"
        and c.bias == "no"
        and not c.lse
        and not c.dropout
        and not c.logits
        and not c.sink
        # The QR async default policy requires a non-empty K/V LDS
        # distribution.  For Dq=Dv=192, the wider M tiles and N<96 shapes
        # generated by the generic rule set violate that compile-time
        # constraint. Keep only the 15 combinations verified to instantiate
        # on gfx942, then remove the two known correctness failures below.
        and c.tile_m0 in (32, 64, 192)
        and c.tile_n0 in (96, 128, 192, 256, 384)
        # (192,128) is fast but leaves complete GQA output heads unwritten;
        # (192,256) produces NaN output. Exclude both correctness failures
        # from performance searches even though they compile on gfx942.
        and (c.tile_m0, c.tile_n0) not in ((192, 128), (192, 256))
    )
